[package]
name = "vss-client"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
homepage = "https://lightningdevkit.org/"
repository = "https://github.com/lightningdevkit/vss-rust-client"
description = "Client-side library to interact with Versioned Storage Service (VSS)."
keywords = ["vss", "bitcoin", "lightning", "ldk", "bdk"]
categories = ["web-programming::http-client", "cryptography::cryptocurrencies"]

build = "build.rs"

[dependencies]
prost = "0.11.6"
reqwest = { version = "0.11.13", features = ["rustls-tls"] }

[build-dependencies]
prost-build = { version = "0.8.0" }
reqwest =  { version = "0.11.13", features = ["blocking"] }

[dev-dependencies]
mockito = "0.31.1"
tokio = { version = "1.22.0", features = ["macros"]}

[features]
genproto = []
